### ISSUE TITLE
vRhyme_nucmer_delta_parsed.tsv not found

### ISSUE THREAD

**Issue by XiongGZ** [AnantharamanLab/vRhyme#12]
**Version:** Version 1.1.0 (March 2022)

**Command:** `vRhyme -t 28 --method longest -i $Assemble/final.contigs.fa -g $Gene_predict/nucl.fa -p $Gene_predict/prot.fa -r $Binning/trimmed_1.fastq $Binning/trimmed_2.fastq -o $Binning/vrhyme`

**Error report:**
`Traceback (most recent call last):
  File "/home/xiongguangzhou/Software/miniconda3/envs/vrhyme/bin/vRhyme", line 541, in <module>
    code, original, sequences = derep_stuff.derep_stuff_longest(in_fasta, int(threads), interest_list, folder, base, derep_len, nuc_c, nuc_b, nuc_g, nuc_split, derep_id, derep_frac, sketch_k, sketch_s, iterations)
  File "/home/xiongguangzhou/Software/miniconda3/envs/vrhyme/bin/derep_stuff.py", line 852, in derep_stuff_longest
    clusters_100_dict, original_seqs, _ = nucmer_filter_1_stuff(original_seqs, folder)
  File "/home/xiongguangzhou/Software/miniconda3/envs/vrhyme/bin/derep_stuff.py", line 327, in nucmer_filter_1_stuff
    with open(folder + "vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv", "r") as coords:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/xiongguangzhou/01.Soil/Metagenome/1-1/05.Binning/vrhyme/vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv'`

Can you help me?
Thanks!

**Comment by KrisKieft** [comment]
Please check out Issue #2 for a potential solution.

**Comment by XiongGZ** [comment]
After i remove `--method`, a new error report

**Command:**
`vRhyme -t 48 --model hybrid --method none -i $Virus_identify/virus.contigs.fa -g $Gene_predict/nucl.fa -p $Gene_predict/prot.fa -r $Binning/Trimmed_1.fastq $Binning/Trimmed_2.fastq -o $Binning/vrhyme`

**Error report:**
```
cat: /data4/xiongguangzhou/01.Soil/Metagenome/1-1/05.Binning/vrhyme/vRhyme_sam_files/Trimmed_1.sam: No such file or directory
rm: cannot remove ‘/data4/xiongguangzhou/01.Soil/Metagenome/1-1/05.Binning/vrhyme/vRhyme_sam_files/Trimmed_1.sam’: No such file or directory

Error. No file(s) for coverage information were identified. Check coverage inputs (c/b/s/r/u/v). Exiting.
```

There was no output in `vRhyme_sam_files` directory.
It seems the alignment process did not work.

**Test the Installation**
test_vRhyme.py (test run)
```

  Python Dependencies
  -------------------
  scikit-learn: Success (v1.1.1)
  numpy: Success (v1.22.4)
  numba: Success (v0.55.2)
  pandas: Success (v1.4.2)
  pysam: Success (v0.19.1)
  networkx: Success (v2.8.4)


  Program Dependencies
  --------------------
  mmseqs: Success
  samtools: Success  prodigal: Success
  mash: Success
  nucmer: Success
  bowtie2: Success
  bwa: Success


  Machine Learning Models
  -----------------------
  NN model: Success
  ET model: Success

```
