### ISSUE TITLE
I encountered an error using the script `coverage_table_convert.py`

### ISSUE THREAD

**Issue by rdenise** [AnantharamanLab/vRhyme#20]
## Description

I encountered an error using the script `coverage_table_convert.py` with the following command line:

```bash
coverage_table_convert.py -i comparison_binning/genomad/databases/jgi_matrix/contigs_split/jgi.ZSM103.jgi -o comparison_binning/genomad/databases/jgi_matrix/contigs_split/jgi.ZSM103.vRhyme.jgi
```

The error message is:

```python3
Traceback (most recent call last):
File "miniconda3/envs/vrhyme/bin/coverage_table_convert.py", line 43, in <module>
convert(args.i[0], args.o[0])
File "miniconda3/envs/vrhyme/bin/coverage_table_convert.py", line 26, in convert
sd = float(line[n+1])**0.5
IndexError: list index out of range
```

## Steps to Reproduce

1. Run the command line provided above

## Actual Behaviour

An `IndexError` is raised, indicating that the list `line` does not have the expected number of elements.

## Additional Information

- Software version: vRhyme v1.1.0 (installed by conda)
- OS: Ubuntu 22.04.1 LTS

[jgi.ZSM103.jgi.zip](https://github.com/AnantharamanLab/vRhyme/files/10674684/jgi.ZSM103.jgi.zip)

**Comment by KrisKieft** [comment]
Hi, 

Thank you for attaching the file. It looks like the JGI coverage table you have is missing the variance column, which ends in "-var". This should be standard column in `jgi_summarize_bam_contig_depths --outputDepth`. vRhyme assumes the input JGI coverage file has 5 total column.
