### ISSUE TITLE
Program trying to read from non-existing output file

### ISSUE THREAD

**Issue by ghost** [AnantharamanLab/vRhyme#21]
Hi there,

I ran vRhyme on several hundreds of samples, and all went smoothly except for one specific problem file, wherein the program seems to write to output files but tries to read from a non-existing intermediate file. 

The err output file says:
```
Traceback (most recent call last):
  File "/users/mhauer1/miniconda3/envs/vRhyme2/bin/vRhyme", line 1017, in <module>
    final, binned_seqs, bins_count, best_score, binned_prots, binned_redundancy = score_stuff.final_bin(folder, best, scoring, mapper, uniques, uniques_info)
  File "/gpfs/home/mhauer1/miniconda3/envs/vRhyme2/bin/score_stuff.py", line 146, in final_bin
    with open(f'{folder}{final}.vRhyme-bins.tsv', 'r') as infile, open(f'{folder}vRhyme_best_bins.{final}.membership.tsv', 'w') as outfile, open(f'{folder}vRhyme_best_bins.{final}.summary.tsv', 'w') as summary:
FileNotFoundError: [Errno 2] No such file or directory: 'I16_1016/13.vRhyme-bins.tsv
```

When I look at the contents of the I16_1016 output directory, it appears vRhyme has produced these *.vRhyme-bins.tsv files for values 1 through 12, and then 18, 19, but not 13-17. 

When I open the log file, it shows that the program always ends at `"2.67          Extracting binning summary statistics for each iteration"`.

Any idea what might be going on here? I am using vRhyme 1.1.0, and almost all of the other samples I ran worked without any issues. Thank you!

**Comment by cody-mar10** [comment]
Hi @minna-miha 

I am not the original vRhyme author, but I can try to help you. I do not have an immediate guess as to what could be happening, especially since this is only a problem for 1 of your inputs. It seems the immediate problem is that iteration 13 is selected as the best binning iteration, but the file no longer exists.

If possible, providing the inputs you used would be the easiest way to figure this out since I could reproduce your results locally, but if that is not possible can you provide the following information:
- In your output directory, can you confirm that the file "vRhyme_alternate_bins/vRhyme_bin_scoring.tsv" exists and has iterations 0-19 present? Or are iterations 13-17 missing from that file as well? If so, then the problem is earlier in the code. There is a step a few lines above that should generate `[0-19].vRhyme-bins.tsv`.

**Comment by MalickNdiye** [comment]
Hi

I have the same problem. looks like vRhyme doesn't produce the 12.vRhyme-bins.tsv file. It produces the files [0-11].vRhyme-bins.tsv, then skips to 13.vRhyme-bins.tsv. It happens on all the samples on which I test it, so I guess it's a bug. Somebody has an idea on how to fix this problem?

**Comment by KrisKieft** [comment]
Hi,

I'm not sure what is causing the issue. Are you able to provide sample data that the error occurs with? Thanks

**Comment by actledge** [comment]
Hi,

I met similar error, 
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/1.vRhyme-bins.tsv

below is the text in vRhyme_bin_scoring.tsv , it seems that *.vRhyme-bins.tsv of itertions with score==-1 were not generated:

iteration   sequences   redundancy  bins    proteins    score
1   0   0   0   0   -1
2   0   0   0   0   -1
3   0   0   0   0   -1
5   0   0   0   0   -1
6   0   0   0   0   -1
8   0   0   0   0   -1
10  0   0   0   0   -1
12  0   0   0   0   -1
13  0   0   0   0   -1
15  0   0   0   0   -1
16  0   0   0   0   -1
17  0   0   0   0   -1
18  0   0   0   0   -1
0   115 347 50  5327    -1.218
4   115 347 50  5327    -1.218
7   115 347 50  5327    -1.218
11  115 347 50  5327    -1.218
14  115 347 50  5327    -1.218
19  115 347 50  5327    -1.218
9   28  127 14  1359    -1.5339

**Comment by actledge** [comment]
Hi,

I met similar error, 
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/1.vRhyme-bins.tsv

below is the text in vRhyme_bin_scoring.tsv , it seems that *.vRhyme-bins.tsv of itertions with score==-1 were not generated, included the :

iteration   sequences   redundancy  bins    proteins    score
1   0   0   0   0   -1
2   0   0   0   0   -1
3   0   0   0   0   -1
5   0   0   0   0   -1
6   0   0   0   0   -1
8   0   0   0   0   -1
10  0   0   0   0   -1
12  0   0   0   0   -1
13  0   0   0   0   -1
15  0   0   0   0   -1
16  0   0   0   0   -1
17  0   0   0   0   -1
18  0   0   0   0   -1
0   115 347 50  5327    -1.218
4   115 347 50  5327    -1.218
7   115 347 50  5327    -1.218
11  115 347 50  5327    -1.218
14  115 347 50  5327    -1.218
19  115 347 50  5327    -1.218
9   28  127 14  1359    -1.5339

> Hi @minna-miha
> 
> I am not the original vRhyme author, but I can try to help you. I do not have an immediate guess as to what could be happening, especially since this is only a problem for 1 of your inputs. It seems the immediate problem is that iteration 13 is selected as the best binning iteration, but the file no longer exists.
> 
> If possible, providing the inputs you used would be the easiest way to figure this out since I could reproduce your results locally, but if that is not possible can you provide the following information:
> 
> * In your output directory, can you confirm that the file "vRhyme_alternate_bins/vRhyme_bin_scoring.tsv" exists and has iterations 0-19 present? Or are iterations 13-17 missing from that file as well? If so, then the problem is earlier in the code. There is a step a few lines above that should generate `[0-19].vRhyme-bins.tsv`.

Hi,

I met similar error,
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/1.vRhyme-bins.tsv

below is the text in vRhyme_bin_scoring.tsv , it seems that *.vRhyme-bins.tsv of itertions with score==-1 were not generated:

iteration sequences redundancy bins proteins score
1 0 0 0 0 -1
2 0 0 0 0 -1
3 0 0 0 0 -1
5 0 0 0 0 -1
6 0 0 0 0 -1
8 0 0 0 0 -1
10 0 0 0 0 -1
12 0 0 0 0 -1
13 0 0 0 0 -1
15 0 0 0 0 -1
16 0 0 0 0 -1
17 0 0 0 0 -1
18 0 0 0 0 -1
0 115 347 50 5327 -1.218
4 115 347 50 5327 -1.218
7 115 347 50 5327 -1.218
11 115 347 50 5327 -1.218
14 115 347 50 5327 -1.218
19 115 347 50 5327 -1.218
9 28 127 14 1359 -1.5339

**Comment by cody-mar10** [comment]
How many viruses are you trying to bin? I am not sure what specifically deletes the iterations, but the results suggest that the optimal binning is actually no binning, which tends to happen when trying to bin a small number of viral contigs.

**Comment by clementcoclet** [comment]
Hi,

I have the same issue:
`51.7          Extracting binning summary statistics for each iteration
Traceback (most recent call last):
  File "/clusterfs/jgi/groups/science/homes/ccoclet/micromamba/envs/mvp/bin/vRhyme", line 1017, in <module>
    final, binned_seqs, bins_count, best_score, binned_prots, binned_redundancy = score_stuff.final_bin(folder, best, scoring, mapper, uniques, uniques_info)
  File "/clusterfs/jgi/groups/science/homes/ccoclet/micromamba/envs/mvp/bin/score_stuff.py", line 146, in final_bin
    with open(f'{folder}{final}.vRhyme-bins.tsv', 'r') as infile, open(f'{folder}vRhyme_best_bins.{final}.membership.tsv', 'w') as outfile, open(f'{folder}vRhyme_best_bins.{final}.summary.tsv', 'w') as summary:
FileNotFoundError: [Errno 2] No such file or directory: 'DEVAKI_YELLOWSTONE_PROJECT/07_BINNING/07A_vRHYME_OUTPUT/12.vRhyme-bins.tsv'`.

12.vRhyme-bins.tsv is not generated while I have the `vRhyme_alternate_bins/vRhyme_bin_scoring.tsv` and I am trying to bin a large number of viral sequences (n = 8853). I also attach the text in vRhyme_bin_scoring.tsv:


`iteration       sequences       redundancy      bins    proteins        score

12      0       0       0       0       -1

15      0       0       0       0       -1

16      0       0       0       0       -1

18      0       0       0       0       -1

0       783     624     297     8445    -1.1079

4       783     624     297     8445    -1.1079

7       783     624     297     8445    -1.1079

11      783     624     297     8445    -1.1079

14      783     624     297     8445    -1.1079

19      783     624     297     8445    -1.1079

9       554     439     221     6052    -1.1679

5       452     424     184     5153    -1.2735

1       229     274     95      2834    -1.436

6       229     274     95      2834    -1.436

10      229     274     95      2834    -1.436

13      229     274     95      2834    -1.436

17      229     274     95      2834    -1.436

8       112     155     48      1456    -1.5409

2       22      67      11      419     -1.9412

3       22      67      11      419     -1.9412`

Thank you,
Clément

**Comment by XinyuGuokk** [comment]
> Hi @minna-miha  嗨 @minna-miha
> 
> I am not the original vRhyme author, but I can try to help you. I do not have an immediate guess as to what could be happening, especially since this is only a problem for 1 of your inputs. It seems the immediate problem is that iteration 13 is selected as the best binning iteration, but the file no longer exists.我不是原始的 vRhyme 作者，但我可以尝试帮助你。我无法立即猜测发生了什么，特别是这仅是你输入中的一个问题。看起来当前的问题是迭代 13 被选为最佳分箱迭代，但该文件已不存在。
> 
> If possible, providing the inputs you used would be the easiest way to figure this out since I could reproduce your results locally, but if that is not possible can you provide the following information:如果可能的话，提供你使用的输入将是最容易解决这个问题的方式，因为我可以在本地重现你的结果，但如果不可能，你能提供以下信息吗：
> 
> * In your output directory, can you confirm that the file "vRhyme_alternate_bins/vRhyme_bin_scoring.tsv" exists and has iterations 0-19 present? Or are iterations 13-17 missing from that file as well? If so, then the problem is earlier in the code. There is a step a few lines above that should generate `[0-19].vRhyme-bins.tsv`.在你的输出目录中，能否确认文件 "vRhyme_alternate_bins/vRhyme_bin_scoring.tsv" 存在并且包含迭代 0-19 的数据？或者该文件是否也缺少迭代 13-17 的数据？如果是这样，那么问题出在代码的前面部分。几行上面的步骤应该生成 `[0-19].vRhyme-bins.tsv` 。

Hello, I've run into the same issue too. I have 178 metagenomic BAM files for binning, and when I specify all 178 with the -b option, the iteration files like [12,15,16,18,20].vRhyme-bins.tsv just won't generate—no matter how many times I try. But if I limit the input to 150 BAM files or fewer, I can get all 20 iteration TSV files and the binning works fine. Any ideas?

**Comment by shaconn** [comment]
Hello,

Was this issue ever resolved? I am currently running vRhyme v1.1.0 and I am being met with the same issue. I am running it in the [MVP](https://gitlab.com/ccoclet/mvp) wrapper, but I am still seeing issues with certain bin scoring iteration files being empty. It seems like vRhyme is then picking those empty files as some of the best-scoring bins, then attempting to use them as the best bins. But with nothing present, it is failing. Here is my log file from the run:

```
Date:     2026-08-11 (y-m-d)
Start:    10:05:40   (h:m:s)
Program:  vRhyme v1.1.0


Time (min) |  Log                                                   
--------------------------------------------------------------------
0.0           Initializing and validating vRhyme parameters
0.07          Extracting coverage information from BAM files
1.49          Coverage extraction complete. Generating coverage table
1.5           Performing pairwise coverage comparisons
3.03          Running Prodigal on filtered sequences
3.58          Generating codon usage features
3.58          Generating nucleotide features
3.63          Performing pairwise distance calculations
3.64          Performing machine learning classification
3.71          Generating networks of bins
3.74          Extracting information for all possible unique bins
3.74          Running mmseqs2 linclust for bin redundancy scoring
3.84          Parsing linclust protein clusters
3.84          Scoring all possible unique bins
3.85          Identifying best set of bins from 20 iterations
3.85          Extracting binning summary statistics for each iteration
/storage/work/stc5395/.conda/envs/mvip/bin/vRhyme:16: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/storage/work/stc5395/.conda/envs/mvip/bin/vRhyme", line 1017, in <module>
    final, binned_seqs, bins_count, best_score, binned_prots, binned_redundancy = score_stuff.final_bin(folder, best, scoring, mapper, uniques, uniques_info)
  File "/storage/work/stc5395/.conda/envs/mvip/bin/score_stuff.py", line 146, in final_bin
    with open(f'{folder}{final}.vRhyme-bins.tsv', 'r') as infile, open(f'{folder}vRhyme_best_bins.{final}.membership.tsv', 'w') as outfile, open(f'{folder}vRhyme_best_bins.{final}.summary.tsv', 'w') as summary:
FileNotFoundError: [Errno 2] No such file or directory: '/storage/home/stc5395/scratch/BordensteinVegVirome/mvp/bulk/07_BINNING/07A_vRHYME_OUTPUT/12.vRhyme-bins.tsv'

Start Time: 2026-08-11 10:05:39
```

Then, when you inspect the bin iterations we see the following:

```
$ wc -l *.vRhyme-bins.tsv | sort -k1,1n | tail -20
     4 2.vRhyme-bins.tsv
     4 3.vRhyme-bins.tsv
    13 8.vRhyme-bins.tsv
    68 1.vRhyme-bins.tsv
    68 10.vRhyme-bins.tsv
    68 13.vRhyme-bins.tsv
    68 17.vRhyme-bins.tsv
    68 6.vRhyme-bins.tsv
   280 5.vRhyme-bins.tsv
   713 9.vRhyme-bins.tsv
  1381 0.vRhyme-bins.tsv
  1381 11.vRhyme-bins.tsv
  1381 19.vRhyme-bins.tsv
  1381 4.vRhyme-bins.tsv
  1381 7.vRhyme-bins.tsv
  1382 14.vRhyme-bins.tsv
  9641 total
```

Interesting to note that this was done using the viral contigs identified from the bulk metagenome. I ran the same analysis on my matched viral-enriched samples and did not run into this issue.

**Comment by KrisKieft** [comment]
I'm not sure what is going on without sample data that can re-create the issue. A solution I could implement is to ignore all iterations that are not generated, but that doesn't solve any potential issue(s) that cause them to be missing. How many samples (coverage files, alignment files, etc) are you inputting? Based on the most recent response of using >100 samples it could potentially be a memory issue.

Try:
1) reduce `--iter` or set `--iter 10`
2) reduce `-t`
3) reduce number of samples (as a test)
