### ISSUE TITLE
i made a mistake. i have no idea with it. need some help

### ISSUE THREAD

**Issue by liucong2016** [AnantharamanLab/vRhyme#24]
(vRhyme) nohup vRhyme -i /home/liu-c/virus-data/tuanjuti-virome/virus-otu-23.4/virus-final.fa -g /home/liu-c/virus-data/tuanjuti-virome/virus-otu-23.4/virus-final.ffn -p /home/liu-c/virus-data/tuanjuti-virome/virus-otu-23.4/virus-final.faa -r total-fastq/*.fastq -t 40 -o out-23.7.6 --method longest

/software1/envs/vRhyme/bin/vRhyme:16: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/software1/envs/vRhyme/bin/vRhyme", line 960, in <module>
    net_data = machine_stuff.machine_stuff(distances, presets, model_method, pairs_machine, cohen_machine, iterations, cohen_check)
  File "/software1/envs/vRhyme/bin/machine_stuff.py", line 73, in machine_stuff
    model_ET = pickle.load(read_model_ET)
  File "sklearn/tree/_tree.pyx", line 714, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1418, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]

**Comment by KrisKieft** [comment]
Hi,

What is your version of sklearn?

**Comment by liucong2016** [comment]
> 

Name: scikit-learn
Version: 1.3.0

**Comment by KrisKieft** [comment]
It's possible this version has changed significantly since development. I'd suggest installing the version listed in the Readme and see if that helps.

**Comment by liucong2016** [comment]
> It's possible this version has changed significantly since development. I'd suggest installing the version listed in the Readme and see if that helps.

Hi, When I downgrade the version of scikit-learn to 0.24 and run the program again, with the following code, I still encounter an error.
(vRhyme) nohup vRhyme -i /home/liu-c/virus-data/tuanjuti-virome/virus-otu-23.4/virus-final.fa -g /home/liu-c/virus-data/tuanjuti-virome/virus-otu-23.4/virus-final.ffn -p /home/liu-c/virus-data/tuanjuti-virome/virus-otu-23.4/virus-final.faa -r total-fastq/*.fastq -t 40 -o out-23.7.7 --method longest

/software1/envs/vRhyme/bin/vRhyme:16: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources


there is still somothing wrong.

**Comment by KrisKieft** [comment]
Did any errors occur or just a warning?

**Comment by CarlosNavr** [comment]
Hello.

Just wanted to comment that I had the same problem, downgraded scikit-learn and it worked. No errors, just that warning.

**Comment by liucong2016** [comment]
thanks a lot. i will try it again.

**Comment by Tina-MengyingWANG** [comment]
Hello.
May I ask how you downgraded scikit-learn? 
I installed vRhyme following the full instruction with 'pip install .'. 
However when I tried to downgrade scikit-learn using 'conda install scikit-learn=0.23.0', all the packages including 'vRhyme=1.1.0' installed by 'pip install .' in the conda env can not be found. 

$ test_vRhyme.py
-bash: /media/WMY/2_software/miniconda3/envs/vrhyme_1.1.0/bin/test_vRhyme.py: /media/WMY/2_software/miniconda3/envs/vrhyme_1.1.0/bin/python3.10: bad interpreter: No such file or directory

**Comment by CarlosNavr** [comment]
Hello there

I simply used pip install scikit-learn==version  while in the conda environment.

El 21 set. 2023, a les 16:55, Tina-MengyingWANG ***@***.***> va escriure:



Hello.
May I ask how you downgraded scikit-learn?
I installed vRhyme following the full instruction with 'pip install .'.
However when I tried to downgrade scikit-learn using 'conda install scikit-learn=0.23.0', all the packages including 'vRhyme=1.1.0' installed by 'pip install .' in the conda env can not be found.

$ test_vRhyme.py
-bash: /media/WMY/2_software/miniconda3/envs/vrhyme_1.1.0/bin/test_vRhyme.py: /media/WMY/2_software/miniconda3/envs/vrhyme_1.1.0/bin/python3.10: bad interpreter: No such file or directory

**Comment by Tina-MengyingWANG** [comment]
Thank you so much! I will try it again.

**Comment by Sanrrone** [comment]
using scikit-learn=0.23.0 didin't work for me, I just downgraded from version 1.3 to 1.2 and works perfectly :D

**Comment by AndAvia** [comment]
> May I ask how you downgraded scikit-learn?



> Hello.
> 
> Just wanted to comment that I had the same problem, downgraded scikit-learn and it worked. No errors, just that warning.

May I ask what you downgraded scikit-learn version?
